"""Initial schema: digital_object and relationship tables.

Revision ID: 0001
Revises:     (none — this is the first migration)
Create Date: 2024-01-01 00:00:00.000000

Creates two tables:
  - `digital_object`: stores all research entities (source datasets and related objects).
    The `pids` JSONB column holds a list of PID dicts and has a GIN index for fast
    PostgreSQL `@>` containment queries used in PID deduplication.

  - `relationship`: directed edges between digital_objects.
    Unique constraint on (source_id, target_id, relation_type) prevents duplicate edges
    of the same type while allowing the same pair to be linked by multiple types.

This migration is hand-written (not autogenerated by Alembic) to correctly express
the GIN index, which `alembic revision --autogenerate` cannot produce for JSONB columns.
Do not use `alembic revision --autogenerate` for this project without careful review.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "digital_object",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("pids", JSONB(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("titles", JSONB(), nullable=True),
        sa.Column("creators", JSONB(), nullable=True),
        sa.Column("keywords", JSONB(), nullable=True),
        sa.Column("topics", JSONB(), nullable=True),
        sa.Column("access", JSONB(), nullable=True),
        sa.Column("methods", JSONB(), nullable=True),
        sa.Column("source_local_id", sa.Text(), nullable=True),
        sa.Column("openaire_id", sa.Text(), nullable=True),
        sa.Column("openalex_id", sa.Text(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("fwci", sa.Float(), nullable=True),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("raw_responses", JSONB(), nullable=False, server_default="{}"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_checked",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    # GIN index for PID containment queries (@> operator)
    op.execute("CREATE INDEX idx_digital_object_pids ON digital_object USING GIN (pids)")

    # btree indexes for cache freshness and enrichment lookups
    op.create_index("idx_digital_object_last_checked", "digital_object", ["last_checked"])
    op.create_index("idx_digital_object_openaire_id", "digital_object", ["openaire_id"])
    op.create_index("idx_digital_object_openalex_id", "digital_object", ["openalex_id"])

    op.create_table(
        "relationship",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "source_id",
            sa.Integer(),
            sa.ForeignKey("digital_object.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "target_id",
            sa.Integer(),
            sa.ForeignKey("digital_object.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("relation_type", sa.Text(), nullable=False),
        sa.Column("provenance", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("source_id", "target_id", "relation_type", name="uq_relationship_edge"),
    )

    op.create_index("idx_relationship_source_id", "relationship", ["source_id"])
    op.create_index("idx_relationship_target_id", "relationship", ["target_id"])


def downgrade() -> None:
    op.drop_table("relationship")
    op.drop_table("digital_object")
