"""Replace openaire_id / openalex_id columns with external_ids JSONB.

Revision ID: 0002
Revises:     0001
Create Date: 2024-01-02 00:00:00.000000

Motivation:
  The original schema had two flat Text columns for external system identifiers
  (`openaire_id`, `openalex_id`).  Every new external system (DataCite, Crossref,
  ORCID, Zenodo, etc.) would require another migration.  This migration replaces
  them with a single `external_ids` JSONB column modelled after the existing `pids`
  column:

      [{"source": "openaire", "id": "50|doi_dedup___::8ec9..."},
       {"source": "openalex", "id": "https://openalex.org/W123"}]

  The `source` field is the dedup key — only one entry per source is stored,
  and newer values overwrite older ones on each enrichment pass.

Steps:
  1. Add `external_ids JSONB NOT NULL DEFAULT '[]'`
  2. Back-fill from the old columns using jsonb_build_array / jsonb_build_object
  3. Drop old btree indexes (they were never used in SQL WHERE clauses)
  4. Drop old columns
  5. Add GIN index on `external_ids` for future @> containment queries

This migration is hand-written (not autogenerated) to use PostgreSQL's
`jsonb_build_array` / `jsonb_build_object` functions and the GIN index declaration.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1 — add the new column with an empty-array default.
    op.add_column(
        "digital_object",
        sa.Column("external_ids", JSONB(), nullable=False, server_default="[]"),
    )

    # Step 2 — back-fill from old columns.
    op.execute("""
        UPDATE digital_object
        SET external_ids = (
            CASE
                WHEN openaire_id IS NOT NULL AND openalex_id IS NOT NULL
                THEN jsonb_build_array(
                         jsonb_build_object('source', 'openaire', 'id', openaire_id),
                         jsonb_build_object('source', 'openalex',  'id', openalex_id))
                WHEN openaire_id IS NOT NULL
                THEN jsonb_build_array(
                         jsonb_build_object('source', 'openaire', 'id', openaire_id))
                WHEN openalex_id IS NOT NULL
                THEN jsonb_build_array(
                         jsonb_build_object('source', 'openalex', 'id', openalex_id))
                ELSE '[]'::jsonb
            END
        )
    """)

    # Step 3 — drop old btree indexes.
    op.drop_index("idx_digital_object_openaire_id", table_name="digital_object")
    op.drop_index("idx_digital_object_openalex_id", table_name="digital_object")

    # Step 4 — drop old columns.
    op.drop_column("digital_object", "openaire_id")
    op.drop_column("digital_object", "openalex_id")

    # Step 5 — GIN index for containment queries on the new column.
    op.execute(
        "CREATE INDEX idx_digital_object_external_ids "
        "ON digital_object USING GIN (external_ids)"
    )


def downgrade() -> None:
    op.drop_index("idx_digital_object_external_ids", table_name="digital_object")

    op.add_column(
        "digital_object",
        sa.Column("openaire_id", sa.Text(), nullable=True),
    )
    op.add_column(
        "digital_object",
        sa.Column("openalex_id", sa.Text(), nullable=True),
    )

    # Restore values from external_ids.
    op.execute("""
        UPDATE digital_object
        SET
            openaire_id = (
                SELECT e->>'id'
                FROM jsonb_array_elements(external_ids) AS e
                WHERE e->>'source' = 'openaire'
                LIMIT 1
            ),
            openalex_id = (
                SELECT e->>'id'
                FROM jsonb_array_elements(external_ids) AS e
                WHERE e->>'source' = 'openalex'
                LIMIT 1
            )
    """)

    op.create_index("idx_digital_object_openaire_id", "digital_object", ["openaire_id"])
    op.create_index("idx_digital_object_openalex_id", "digital_object", ["openalex_id"])

    op.drop_column("digital_object", "external_ids")
